eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
spring:
  application:
    name: config-server
  cloud:
    config:
     label: master
     server:
      git:
        uri: https://github.com/daniel-tian/SpringCloudConfig/
        searchPatchs: / 
server:
  port: 8888

